name: test
on:
  push:
    paths:
      - 'tests/**'
  workflow_dispatch:
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.11'
      - name: Install the necessary packages
        run: 
          pip install -r requirements.txt
      - name: Run the TestSuite
        run: py.test

      
    
  
